### ISSUE TITLE
Misspellings in README.md

### ISSUE THREAD

**Issue by robertfchapman** [shalomb/ansible-systemd-timesyncd#4]
Very good work on this Ansible Role and Git Repo.

I found some misspellings in your readme.md.

In Dependencies   section:
Debian-based running systemd-timesyncd (NOTE: systemd on the Redhat family (RHEL/Fedora/CentOs) is not compiled with timesyncd for NTP **syncrhonization** and uses chrony **instelad**)

Should be
Debian-based running systemd-timesyncd (NOTE: systemd on the Redhat family (RHEL/Fedora/CentOs) is not compiled with timesyncd for NTP **synchronization** and uses chrony **instead**)

Again, thanks for your hard work and contribution to Ansible, and Open Source.

**Comment by shalomb** [comment]
Thank you for reporting this. These should be addressed in master as the [build](https://travis-ci.org/github/shalomb/ansible-systemd-timesyncd/builds/764285215) passes and fix is merged.
